spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  application:
    name: api_pet
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: false
    contexts: dev
  jpa:
    show-sql: true
